package com.lindzh.hasting.webui.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.lindzh.hasting.webui.pojo.LimitInfo;

/**
 * @author AutoGenerated by lindzh
 * 2017年02月15日 14:27
 */
public interface LimitInfoDao {

	public int addLimitInfo(LimitInfo obj);

	public LimitInfo getById(@Param("id")long id);
	
	public int updateById(@Param("obj")LimitInfo obj);
	
	public int deleteById(@Param("id")long id);
	
	
	public List<LimitInfo> getListByAppId(@Param("appId")long appId,@Param("limit")int limit,@Param("offset") int offset);
	
	public long getCountByAppId(@Param("appId")long appId);



	public int deleteByAppId(@Param("appId")long appId);

	public int batchAdd(@Param("limits")List<LimitInfo> limits);
	
}
