package com.lindzh.hasting.webui.dao;

import java.util.List;

import com.lindzh.hasting.webui.pojo.ServiceConsumerInfo;
import org.apache.ibatis.annotations.Param;

/**
 * @author AutoGenerated by lindzh
 * 2016年12月15日 16:55
 */
public interface ServiceConsumerInfoDao {

	public int addServiceConsumerInfo(ServiceConsumerInfo obj);

	public ServiceConsumerInfo getById(@Param("id")long id);
	
	public int updateById(@Param("obj")ServiceConsumerInfo obj);
	
	public int deleteById(@Param("id")long id);
	
	
	public List<ServiceConsumerInfo> getListByServiceId(@Param("serviceId")long serviceId,@Param("limit")int limit,@Param("offset") int offset);
	
	public long getCountByServiceId(@Param("serviceId")long serviceId);
	
	
	public List<ServiceConsumerInfo> getListByServiceAppId(@Param("serviceAppId")long serviceAppId,@Param("limit")int limit,@Param("offset") int offset);
	
	public long getCountByServiceAppId(@Param("serviceAppId")long serviceAppId);
	
	
	public List<ServiceConsumerInfo> getListByConsumerAppId(@Param("consumerAppId")long consumerAppId,@Param("limit")int limit,@Param("offset") int offset);
	
	public long getCountByConsumerAppId(@Param("consumerAppId")long consumerAppId);
	
	
	public List<ServiceConsumerInfo> getListByConsumerHostId(@Param("comsumerHostId")long comsumerHostId,@Param("limit")int limit,@Param("offset") int offset);
	
	public long getCountByConsumerHostId(@Param("comsumerHostId")long comsumerHostId);


	public int deleteByConsumerAppIdAndHostId(@Param("consumerAppId")long consumeAppId,@Param("comsumerHostId")long consumerHostId);

	/**
	 *
	 * @param pAppId 服务提供者appid
	 * @param pServiceid 服务名称
	 * @param cAppId 服务消费者app
	 * @param cip 服务消费者机器
     * @return
     */
	public ServiceConsumerInfo getConsumer(@Param("serviceAppId")long pAppId,@Param("serviceId")long pServiceid,@Param("consumerAppId")long cAppId,@Param("comsumerHostId")long cHostId);

	public long getServiceConsumeCount(@Param("serviceAppId")long providerAppId,@Param("serviceId")long providerServiceId);
	
}
