package com.lindzh.hasting.webui.dao;

import java.util.List;

import com.lindzh.hasting.webui.pojo.ServiceInfo;
import org.apache.ibatis.annotations.Param;

/**
 * @author AutoGenerated by lindzh
 * 2016年12月15日 16:55
 */
public interface ServiceInfoDao {

	public int addServiceInfo(ServiceInfo obj);

	public ServiceInfo getById(@Param("id")long id);
	
	public int updateById(@Param("obj")ServiceInfo obj);
	
	public int deleteById(@Param("id")long id);
	
	
	public List<ServiceInfo> getListByNameAndAppId(@Param("name")String name,@Param("appId")long appId,@Param("limit")int limit,@Param("offset") int offset);
	
	public long getCountByNameAndAppId(@Param("name")String name,@Param("appId")long appId);
	
	
	public List<ServiceInfo> getListByAppIdAndStatus(@Param("appId")long appId,@Param("status")int status,@Param("limit")int limit,@Param("offset") int offset);
	
	public long getCountByAppIdAndStatus(@Param("appId")long appId,@Param("status")int status);


	public ServiceInfo getByAppIdGroupNameVersion(@Param("appId")long appId,@Param("group")String group,@Param("name") String name,@Param("version") String version);

	public void updateConsumerCount();

	public int updateProviderCount();

	public void updateServiceStatus();


	public List<ServiceInfo> getConsumeServicesByAppId(@Param("appId")long appId);

	public List<ServiceInfo> getProvideServicesByHostId(@Param("hostId")long hostid);

	public List<ServiceInfo> getConsumeServicesByHostId(@Param("hostId")long hostid);

	public List<ServiceInfo> getListByProviderAndConsumerApp(@Param("providerAppId")long providerAppId,@Param("consumerAppId")long consumeAppId);

}
